import { defineType, defineField } from "sanity";

export const gameSchema = defineType({
  name: "game",
  title: "Juego",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Título", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title", maxLength: 96 } }),
    defineField({ name: "description", title: "Descripción", type: "text", rows: 5 }),
    defineField({ name: "rating", title: "Puntuación (0-10)", type: "number" }),
    defineField({ name: "price", title: "Precio", type: "string" }),
    defineField({ name: "original_price", title: "Precio original (sin descuento)", type: "string" }),
    defineField({ name: "discount_percent", title: "Descuento (%)", type: "number" }),
    defineField({ name: "ratings_count", title: "Cantidad de valoraciones", type: "number" }),
    defineField({ name: "pc_requirements_min", title: "Requisitos mínimos", type: "text", rows: 6 }),
    defineField({ name: "pc_requirements_rec", title: "Requisitos recomendados", type: "text", rows: 6 }),
    defineField({ name: "year", title: "Año", type: "number" }),
    defineField({ name: "release_date", title: "Fecha de lanzamiento", type: "string" }),
    defineField({ name: "developer", title: "Desarrollador", type: "string" }),
    defineField({ name: "publisher", title: "Publicador", type: "string" }),
    defineField({ name: "duration", title: "Duración (ej: 60h)", type: "string" }),
    defineField({ name: "players", title: "Jugadores (ej: 1-4)", type: "string" }),
    defineField({ name: "size", title: "Tamaño (ej: 60 GB)", type: "string" }),
    defineField({ name: "mode", title: "Modo de juego", type: "string" }),
    defineField({ name: "languages", title: "Idiomas", type: "string" }),
    defineField({ name: "trailer_url", title: "URL del tráiler", type: "url" }),
    defineField({ name: "genre_names", title: "Nombres de género", type: "array", of: [{ type: "string" }] }),
    defineField({
      name: "features",
      title: "Características",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "title", type: "string", title: "Título" },
          { name: "description", type: "string", title: "Descripción" },
        ],
      }],
    }),
    defineField({ name: "esrb_rating", title: "Clasificación ESRB", type: "string" }),
    defineField({
      name: "tags",
      title: "Etiquetas",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "genres",
      title: "Géneros",
      type: "array",
      of: [{ type: "reference", to: [{ type: "genre" }] }],
    }),
    defineField({
      name: "platforms",
      title: "Plataformas",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "PlayStation 5", value: "PS5" },
          { title: "Xbox Series X", value: "Xbox Series" },
          { title: "Nintendo Switch", value: "Switch" },
          { title: "PC", value: "PC" },
          { title: "PlayStation 4", value: "PS4" },
          { title: "Xbox One", value: "Xbox One" },
        ],
      },
    }),
    defineField({ name: "image", title: "Imagen principal", type: "image" }),
    defineField({ name: "image_url", title: "URL de imagen (RAWG)", type: "url" }),
    defineField({ name: "cover_url", title: "URL de portada (Steam)", type: "url" }),
    defineField({ name: "steam_app_id", title: "Steam App ID", type: "number" }),
    defineField({ name: "screenshots", title: "Capturas del juego", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "gallery", title: "Galería de imágenes", type: "array", of: [{ type: "image" }] }),
  ],
  preview: {
    select: { title: "title", subtitle: "year" },
  },
});
